/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define RPCPROG 0x20000001
#define RPCVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define getNumeroId 1
extern  int * getnumeroid_1(void *, CLIENT *);
extern  int * getnumeroid_1_svc(void *, struct svc_req *);
#define getTicket 2
extern  int * getticket_1(void *, CLIENT *);
extern  int * getticket_1_svc(void *, struct svc_req *);
extern int rpcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getNumeroId 1
extern  int * getnumeroid_1();
extern  int * getnumeroid_1_svc();
#define getTicket 2
extern  int * getticket_1();
extern  int * getticket_1_svc();
extern int rpcprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
