/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define RPCPROG 0x20000099
#define RPCVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define getId 1
extern  int * getid_1(void *, CLIENT *);
extern  int * getid_1_svc(void *, struct svc_req *);
extern int rpcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getId 1
extern  int * getid_1();
extern  int * getid_1_svc();
extern int rpcprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
