/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"

int *
getnumeroid_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result = 0;

	/*
	 * insert server code here
	 */
    result = (result+1) % INT_MAX;

	printf("Enviando id %d\n",result);

	return &result;
}

int *
getticket_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    result = (result+1) % INT_MAX;

	printf("Enviando ticket %d\n",result);

	return &result;
}
